 #ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.0 */
/* https://github.com/olo2000pm/Virtuoso-ESP32-YoRadio */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */
/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define ARDUINO_ESP32S3_DEV

#define L10N_LANGUAGE PL

#define DSP_MODEL DSP_SSD1322
#define TFT_DC 10
#define TFT_CS 9
#define TFT_RST 8
#define BRIGHTNESS_PIN 255
#define NEXTION_RX 255
#define NEXTION_TX 255

#define I2S_LRC 5
#define I2S_DOUT 6
#define I2S_BCLK 7
#define I2S_MCLK 16
#define I2S_INTERNAL false


#define ENC_BTNR 255
#define ENC_BTNL 255
#define ENC_BTNB 255

#define ENC2_BTNR 41
#define ENC2_BTNL 40
#define ENC2_BTNB 39
#define ENC2_INTERNALPULLUP true
#define ENC2_HALFQUARD true

#define IR_PIN			14
#define IR_TIMEOUT      50

#define BT_RELAY_PIN 4

#define BT_MUTE_PIN 18
#define BT_KEY_PIN 17

// VU METER STYLE
// Now controlled via Web Interface (System Settings)
// #define VU_STYLE_PARALLEL - Deprecated, use GUI

// dodać jeśli chcesz wyłaczyć diodę RGB:
#define USE_BUILTIN_LED false
#define LED_BUILTIN_S3 255

#define WAKE_PIN 1

// dodać jesli wyświetlacz to SSD1322 i chcesz mieć odcienie szarości:
#define SSD1322_GRAYSCALE true

// dodać jeśli wyświetlacz to SSD1322 i projekt to Virtuoso:
#define BITRATE_FULL false //---wyłączenie wskaznika BitrateFull (używamy prostego)
#define EXT_WEATHER false //---skrocone informacje pogodowe
#define SDC_CS 255
#define TS_MODEL TS_MODEL_UNDEFINED

#define AUDIOBUFFER_MULTIPLIER2 64
#define DMA_BUFCOUNT 12
#define DMA_BUFCOUNT_PSRAM 24
#define AUDIO_PREFILL_FRAMES 20

#define YOENCODER_DEBOUNCE_US 1500
#define YOENCODER_STABLE_US 0
#endif
